from .alexnet_ecoset import Alexnet_ecoset
from .alexnet_salobjsub import AlexNet_SalObjSub
from .resnet50_ecoset import Resnet50_ecoset
from .resnet18_ecoset import Resnet18_ecoset
from .vgg16_ecoset import VGG16_ecoset
from .openclip import OpenCLIP
from .inception_ecoset import Inception_ecoset
from .official_clip import clip
from .resnet import resnet18
